version: "3"

services:

  elasticsearch:
    image: elasticsearch:7.7.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:7.7.1
    container_name: kibana
    hostname: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.7.1
    container_name: logstash
    hostname: logstash
    ports:
      - 9600:9600
      - 8089:8089
    depends_on:
      - elasticsearch
